server:
  port: 7777
  servlet:
    context-path: /sm-api-gateway

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: SOCIAL_MEDIA
    password: 1
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: SOCIAL_MEDIA

  cloud:
    gateway:
      routes:
        - id: sm-security-manager-route
          uri: http://localhost:8001
          predicates:
            - "Path=/sm-security-manager/**"

        - id: sm-comment-manager-route
          uri: http://localhost:8002
          predicates:
            - "Path=/sm-comment-manager/**"

        - id: sm-like-manager-route
          uri: http://localhost:8003
          predicates:
            - "Path=/sm-like-manager/**"

        - id: sm-post-manager-route
          uri: http://localhost:8004
          predicates:
            - "Path=/sm-post-manager/**"

        - id: sm-todo-manager-route
          uri: http://localhost:8005
          predicates:
            - "Path=/sm-todo-manager/**"

        - id: sm-user-manager-route
          uri: http://localhost:8006
          predicates:
            - "Path=/sm-user-manager/**"
