server:
  port: 7777
  servlet:
    context-path: /sm-api-gateway


spring:
  datasource:
    url: jdbc:oracle:thin:@//XX:1521/XX
    username: XX
    password: XX
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: SOCIAL_MEDIA

  cloud:
    gateway:
      routes:
        - id: sm-security-manager-route
          uri: http://svc-security-manager:8001
          predicates:
            - "Path=/sm-security-manager/**"

        - id: sm-comment-manager-route
          uri: http://svc-comment-manager:8002
          predicates:
            - "Path=/sm-comment-manager/**"

        - id: sm-like-manager-route
          uri: http://svc-like-manager:8003
          predicates:
            - "Path=/sm-like-manager/**"

        - id: sm-post-manager-route
          uri: http://svc-post-manager:8004
          predicates:
            - "Path=/sm-post-manager/**"

        - id: sm-todo-manager-route
          uri: http://svc-todo-manager:8005
          predicates:
            - "Path=/sm-todo-manager/**"

        - id: sm-user-manager-route
          uri: http://svc-user-manager:8006
          predicates:
            - "Path=/sm-user-manager/**"
