server:
  port: 8002
  servlet:
    context-path: /sm-comment-manager

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: SOCIAL_MEDIA
    password: 1
    driver-class-name: oracle.jdbc.OracleDriver

sm:
  microservices:
    sm-user-manager: http://localhost:8006/sm-user-manager

profiles:
  host:
    url: http://localhost:7777

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: SOCIAL_MEDIA
  cloud:
    config:
      failFast: false
      retry:
        maxAttempts: 10
        initialInterval: 3000
        multiplier: 1.5
        maxInterval: 30000
logging:
  level:
    # Config Client logları
    org.springframework.cloud.config.client: DEBUG
    # HTTP request/response detayları
    org.springframework.web: DEBUG
    org.apache.http: DEBUG