server:
  port: 8001
  servlet:
    context-path: /sm-security-manager

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB
    username: SOCIAL_MEDIA
    password: 1
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: SOCIAL_MEDIA
  cloud:
    config:
      failFast: false
      retry:
        maxAttempts: 10
        initialInterval: 3000
        multiplier: 1.5
        maxInterval: 30000
logging:
  level:
    # Config Client logları
    org.springframework.cloud.config.client: DEBUG
    # HTTP request/response detayları
    org.springframework.web: DEBUG
    org.apache.http: DEBUG